_format_version: '2.1'
_transform: true

services:
  - name: mockbin
    url: https://mockbin.org/request
    plugins:
      - name: custom-jwt
        config:
          secret: password
    routes:
      - paths:
          - /
